services:
  db:
    image: postgres:15
    container_name: financa-facil-db
    restart: always
    env_file:
      - ./api/.env.local
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  # --- Serviço do Backend (NestJS) ---
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: financa-facil-api
    ports:
      - "1239:1239"
    depends_on:
      - db
    env_file:
      - ./api/.env.local
    environment:
      POSTGRES_HOST: financa-facil-db
      POSTGRES_PORT: 5432
    volumes:
      - ./api:/api
      - /api/node_modules
      - /api/.dist

  # --- Serviço do Frontend (Next.js) ---
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: financa-facil-app
    ports:
      - "1240:1240"
    depends_on:
      - backend
    env_file:
      - ./app/.env.local
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:1239
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next

volumes:
  pg_data:
